import type {
  Product,
  Collection,
  Testimonial,
  NavLink,
} from "@/types";

// ─── Navigation ──────────────────────────────────────────────────
export const navLinks: NavLink[] = [
  { label: "Shop",         href: "/shop" },
  { label: "Collections",  href: "/collections" },
  { label: "New Arrivals", href: "/shop?filter=new" },
  { label: "Sale",         href: "/shop?filter=sale" },
  { label: "About",        href: "/about" },
];

// ─── Collections ─────────────────────────────────────────────────
export const collections: Collection[] = [
  {
    id: "col-1",
    name: "Premium",
    slug: "premium",
    description: "Light, breathable pieces for the warm season",
    image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&q=80",
    productCount: 24,
  },
  {
    id: "col-2",
    name: "Super Premium",
    slug: "super-premium",
    description: "Sophisticated styles for every occasion",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b5a20?w=800&q=80",
    productCount: 18,
  },
  {
    id: "col-3",
    name: "Premium",
    slug: "premium",
    description: "Everyday wear that never compromises on style",
    image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&q=80",
    productCount: 32,
  },
  {
    id: "col-4",
    name: "Super Premium",
    slug: "super-premium",
    description: "Warm, refined pieces for cooler days",
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80",
    productCount: 20,
  },
];

// ─── Products ────────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "prod-1",
    name: "Classic Linen Kurta",
    slug: "classic-linen-kurta",
    description: "A timeless linen kurta crafted for everyday elegance. Features a relaxed silhouette with fine stitching details.",
    price: 3500,
    compareAtPrice: 4500,
    images: [
      { id: "img-1", url: "https://images.unsplash.com/photo-1604975701397-6365ccbd028a?w=800&q=80", alt: "Classic Linen Kurta", isPrimary: true },
    ],
    variants: [
      { id: "var-1", size: "S", color: "White", colorHex: "#ffffff", stock: 10, price: 3500, sku: "CLK-S-W" },
      { id: "var-2", size: "M", color: "White", colorHex: "#ffffff", stock: 8,  price: 3500, sku: "CLK-M-W" },
      { id: "var-3", size: "L", color: "White", colorHex: "#ffffff", stock: 5,  price: 3500, sku: "CLK-L-W" },
      { id: "var-4", size: "S", color: "Beige", colorHex: "#f5f0e8", stock: 7,  price: 3500, sku: "CLK-S-B" },
    ],
    collectionId: "col-1",
    collection: "Premium",
    tags: ["kurta", "linen", "summer"],
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 124,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-03-01",
  },
  {
    id: "prod-2",
    name: "Premium Formal Shirt",
    slug: "premium-formal-shirt",
    description: "Elevate your formal wardrobe with this crisp, tailored shirt. Made from premium Egyptian cotton.",
    price: 2800,
    compareAtPrice: undefined,
    images: [
      { id: "img-2", url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80", alt: "Premium Formal Shirt", isPrimary: true },
    ],
    variants: [
      { id: "var-5", size: "S", color: "Navy", colorHex: "#1e3a5f", stock: 12, price: 2800, sku: "PFS-S-N" },
      { id: "var-6", size: "M", color: "Navy", colorHex: "#1e3a5f", stock: 10, price: 2800, sku: "PFS-M-N" },
      { id: "var-7", size: "L", color: "Navy", colorHex: "#1e3a5f", stock: 6,  price: 2800, sku: "PFS-L-N" },
    ],
    collectionId: "col-2",
    collection: "Super Premium",
    tags: ["shirt", "formal", "cotton"],
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 89,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-05-10",
  },
  {
    id: "prod-3",
    name: "Relaxed Chino Trousers",
    slug: "relaxed-chino-trousers",
    description: "Versatile chino trousers with a relaxed fit. Perfect for both casual outings and smart-casual looks.",
    price: 3200,
    compareAtPrice: 3800,
    images: [
      { id: "img-3", url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80", alt: "Relaxed Chino Trousers", isPrimary: true },
    ],
    variants: [
      { id: "var-8",  size: "S", color: "Khaki", colorHex: "#c3b091", stock: 9,  price: 3200, sku: "RCT-S-K" },
      { id: "var-9",  size: "M", color: "Khaki", colorHex: "#c3b091", stock: 11, price: 3200, sku: "RCT-M-K" },
      { id: "var-10", size: "L", color: "Olive", colorHex: "#556b2f", stock: 7,  price: 3200, sku: "RCT-L-O" },
    ],
    collectionId: "col-3",
    collection: "Premium",
    tags: ["trousers", "chino", "casual"],
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 67,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-06-01",
  },
  {
    id: "prod-4",
    name: "Wool Blend Overcoat",
    slug: "wool-blend-overcoat",
    description: "A refined wool blend overcoat that combines warmth with timeless sophistication.",
    price: 12000,
    compareAtPrice: 15000,
    images: [
      { id: "img-4", url: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?w=800&q=80", alt: "Wool Blend Overcoat", isPrimary: true },
    ],
    variants: [
      { id: "var-11", size: "M",  color: "Camel", colorHex: "#c19a6b", stock: 4, price: 12000, sku: "WBO-M-C" },
      { id: "var-12", size: "L",  color: "Camel", colorHex: "#c19a6b", stock: 3, price: 12000, sku: "WBO-L-C" },
      { id: "var-13", size: "XL", color: "Grey",  colorHex: "#808080", stock: 5, price: 12000, sku: "WBO-XL-G" },
    ],
    collectionId: "col-4",
    collection: "Super Premium",
    tags: ["coat", "wool", "winter", "luxury"],
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.9,
    reviewCount: 43,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-01-15",
  },
  {
    id: "prod-5",
    name: "Embroidered Lawn Suit",
    slug: "embroidered-lawn-suit",
    description: "Delicate embroidery on premium lawn fabric. A celebration of Pakistani craftsmanship.",
    price: 6500,
    compareAtPrice: 8000,
    images: [
      { id: "img-5", url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80", alt: "Embroidered Lawn Suit", isPrimary: true },
    ],
    variants: [
      { id: "var-14", size: "S", color: "Mint",  colorHex: "#98d8c8", stock: 8, price: 6500, sku: "ELS-S-M" },
      { id: "var-15", size: "M", color: "Mint",  colorHex: "#98d8c8", stock: 6, price: 6500, sku: "ELS-M-M" },
      { id: "var-16", size: "L", color: "Peach", colorHex: "#ffcba4", stock: 9, price: 6500, sku: "ELS-L-P" },
    ],
    collectionId: "col-1",
    collection: "Premium",
    tags: ["lawn", "embroidered", "suit", "summer"],
    isNew: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 156,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-05-20",
  },
  {
    id: "prod-6",
    name: "Structured Blazer",
    slug: "structured-blazer",
    description: "A sharp, structured blazer that commands attention. Crafted with precision for the modern professional.",
    price: 8500,
    compareAtPrice: undefined,
    images: [
      { id: "img-6", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80", alt: "Structured Blazer", isPrimary: true },
    ],
    variants: [
      { id: "var-17", size: "S", color: "Charcoal", colorHex: "#36454f", stock: 5, price: 8500, sku: "SB-S-C" },
      { id: "var-18", size: "M", color: "Charcoal", colorHex: "#36454f", stock: 7, price: 8500, sku: "SB-M-C" },
      { id: "var-19", size: "L", color: "Black",    colorHex: "#000000", stock: 6, price: 8500, sku: "SB-L-B" },
    ],
    collectionId: "col-2",
    collection: "Super Premium",
    tags: ["blazer", "formal", "professional"],
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 78,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-02-28",
  },
  {
    id: "prod-7",
    name: "Cotton Pique Polo",
    slug: "cotton-pique-polo",
    description: "A refined take on the classic polo. Made from premium pique cotton with subtle branding.",
    price: 2200,
    compareAtPrice: undefined,
    images: [
      { id: "img-7", url: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&q=80", alt: "Cotton Pique Polo", isPrimary: true },
    ],
    variants: [
      { id: "var-20", size: "S", color: "White", colorHex: "#ffffff", stock: 15, price: 2200, sku: "CPP-S-W" },
      { id: "var-21", size: "M", color: "White", colorHex: "#ffffff", stock: 12, price: 2200, sku: "CPP-M-W" },
      { id: "var-22", size: "M", color: "Navy",  colorHex: "#1e3a5f", stock: 10, price: 2200, sku: "CPP-M-N" },
      { id: "var-23", size: "L", color: "Navy",  colorHex: "#1e3a5f", stock: 8,  price: 2200, sku: "CPP-L-N" },
    ],
    collectionId: "col-3",
    collection: "Premium",
    tags: ["polo", "cotton", "casual", "summer"],
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.4,
    reviewCount: 210,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-06-10",
  },
  {
    id: "prod-8",
    name: "Cashmere Roll-Neck",
    slug: "cashmere-roll-neck",
    description: "Luxuriously soft cashmere roll-neck. The ultimate winter essential for those who appreciate quality.",
    price: 9800,
    compareAtPrice: 12000,
    images: [
      { id: "img-8", url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80", alt: "Cashmere Roll-Neck", isPrimary: true },
    ],
    variants: [
      { id: "var-24", size: "S", color: "Cream",  colorHex: "#f5f0e8", stock: 4, price: 9800, sku: "CRN-S-C" },
      { id: "var-25", size: "M", color: "Cream",  colorHex: "#f5f0e8", stock: 5, price: 9800, sku: "CRN-M-C" },
      { id: "var-26", size: "M", color: "Walnut", colorHex: "#773f1a", stock: 3, price: 9800, sku: "CRN-M-W" },
    ],
    collectionId: "col-4",
    collection: "Super Premium",
    tags: ["cashmere", "knitwear", "winter", "luxury"],
    isNew: false,
    isFeatured: true,
    isBestSeller: false,
    rating: 5.0,
    reviewCount: 32,
    waist: null,
    length: null,
    bottom: null,
    bgColor: null,
    createdAt: "2024-01-20",
  },
];

// ─── Testimonials ────────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: "t-1",
    name: "Ayesha Mahmood",
    location: "Lahore",
    rating: 5,
    comment: "Denova PK has completely transformed my wardrobe. The quality is outstanding — every piece feels premium and the stitching is immaculate. Will never shop anywhere else.",
    date: "2024-05-15",
  },
  {
    id: "t-2",
    name: "Usman Tariq",
    location: "Karachi",
    rating: 5,
    comment: "Finally a Pakistani brand that truly delivers on its promise of quality. The Formal Edit collection is exceptional. Got so many compliments at the office.",
    date: "2024-06-02",
  },
  {
    id: "t-3",
    name: "Sana Rizvi",
    location: "Islamabad",
    rating: 5,
    comment: "The embroidered lawn suit is absolutely gorgeous. The fabric quality, the embroidery detail, the fit — everything is perfect. Packaging was also very elegant.",
    date: "2024-06-18",
  },
  {
    id: "t-4",
    name: "Bilal Ahmed",
    location: "Rawalpindi",
    rating: 4,
    comment: "Very impressed with the cashmere roll-neck. It is exactly as described — incredibly soft and warm. Fast delivery too. Highly recommend.",
    date: "2024-04-30",
  },
  {
    id: "t-5",
    name: "Fatima Khan",
    location: "Lahore",
    rating: 5,
    comment: "I bought three pieces from the Summer Essentials collection and I love them all. The linen quality is top-notch. This is genuine luxury at a fair price.",
    date: "2024-05-28",
  },
];

// ─── Featured Products (subset) ──────────────────────────────────
export const featuredProducts = products.filter((p) => p.isFeatured);

// ─── New Arrivals (subset) ───────────────────────────────────────
export const newArrivals = products.filter((p) => p.isNew);

// ─── Best Sellers (subset) ───────────────────────────────────────
export const bestSellers = products.filter((p) => p.isBestSeller);

// ─── Mock Orders ───────────────────────────────────────────
import type { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id:          "order-1",
    orderNumber: "DNV12345678",
    userId:      "user-1",
    items: [
      {
        id:        "oi-1",
        productId: "prod-1",
        name:      "Classic Linen Kurta",
        image:     "https://images.unsplash.com/photo-1604975701397-6365ccbd028a?w=400&q=80",
        size:      "M",
        color:     "White",
        price:     3500,
        quantity:  1,
      },
      {
        id:        "oi-2",
        productId: "prod-5",
        name:      "Embroidered Lawn Suit",
        image:     "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&q=80",
        size:      "M",
        color:     "Mint",
        price:     6500,
        quantity:  1,
      },
    ],
    status:      "delivered",
    subtotal:    10000,
    discount:    0,
    shipping:    0,
    total:       10000,
    address: {
      id:         "addr-1",
      userId:     "user-1",
      label:      "Home",
      fullName:   "Ayesha Malik",
      phone:      "+92 300 1234567",
      street:     "House 42, Street 7, DHA Phase 5",
      city:       "Lahore",
      province:   "Punjab",
      postalCode: "54000",
      isDefault:  true,
    },
    paymentMethod: "Cash on Delivery",
    createdAt:   "2024-06-15",
    updatedAt:   "2024-06-19",
  },
  {
    id:          "order-2",
    orderNumber: "DNV12345679",
    userId:      "user-1",
    items: [
      {
        id:        "oi-3",
        productId: "prod-2",
        name:      "Premium Formal Shirt",
        image:     "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
        size:      "L",
        color:     "Navy",
        price:     2800,
        quantity:  2,
      },
    ],
    status:      "shipped",
    subtotal:    5600,
    discount:    0,
    shipping:    250,
    total:       5850,
    address: {
      id:         "addr-1",
      userId:     "user-1",
      label:      "Home",
      fullName:   "Ayesha Malik",
      phone:      "+92 300 1234567",
      street:     "House 42, Street 7, DHA Phase 5",
      city:       "Lahore",
      province:   "Punjab",
      postalCode: "54000",
      isDefault:  true,
    },
    paymentMethod: "Credit Card",
    createdAt:   "2024-07-10",
    updatedAt:   "2024-07-12",
  },
  {
    id:          "order-3",
    orderNumber: "DNV12345680",
    userId:      "user-1",
    items: [
      {
        id:        "oi-4",
        productId: "prod-8",
        name:      "Cashmere Roll-Neck",
        image:     "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80",
        size:      "M",
        color:     "Cream",
        price:     9800,
        quantity:  1,
      },
    ],
    status:      "processing",
    subtotal:    9800,
    discount:    0,
    shipping:    0,
    total:       9800,
    address: {
      id:         "addr-1",
      userId:     "user-1",
      label:      "Home",
      fullName:   "Ayesha Malik",
      phone:      "+92 300 1234567",
      street:     "House 42, Street 7, DHA Phase 5",
      city:       "Lahore",
      province:   "Punjab",
      postalCode: "54000",
      isDefault:  true,
    },
    paymentMethod: "JazzCash",
    createdAt:   "2024-08-01",
    updatedAt:   "2024-08-02",
  },
];